import WebSocket from 'ws';
import { writeFileSync } from 'node:fs';
const [, , url, out, widthArg] = process.argv;
const width = Number(widthArg ?? 1440);
const targets = await (await fetch('http://127.0.0.1:9222/json/list')).json();
const page = targets.find((t) => t.type === 'page');
const ws = new WebSocket(page.webSocketDebuggerUrl, { perMessageDeflate: false });
let id = 0; const pending = new Map();
const send = (method, params = {}) => new Promise((res) => { const m = ++id; pending.set(m, res); ws.send(JSON.stringify({ id: m, method, params })); });
await new Promise((r) => ws.on('open', r));
ws.on('message', (raw) => { const m = JSON.parse(raw.toString()); if (m.id && pending.has(m.id)) pending.get(m.id)(m.result); });
await send('Page.enable');
await send('Emulation.setDeviceMetricsOverride', { width, height: 1500, deviceScaleFactor: 2, mobile: width < 700 });
await send('Page.navigate', { url });
await new Promise((r) => setTimeout(r, 7000));
const sw = await send('Runtime.evaluate', { expression: 'JSON.stringify({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth})', returnByValue: true });
console.log(`${width}px overflow:`, sw.result.value);
const shot = await send('Page.captureScreenshot', { format: 'png' });
writeFileSync(out, Buffer.from(shot.data, 'base64'));
console.log(`wrote ${out}`);
ws.close(); process.exit(0);
